# Random TF 50-50 classifier

做實驗來了解 DataRobot 的各種 glossary 的意義。弄個 2000 x 300 的亂數，其中只有 column 0 (target) 與 1 有關係。當 colomn 1 > 0.5 target 為 True 反之為 False.

本檔歷史

    [Closed] [初學 DNNClassifier 一問](https://note.youdao.com/s/IKTfGqy8)。

    問題: Ynote > 初學 DNNClassifier 一問
    說明：
    答案: DataRobot 的 feature impact , feature effect 之類。
    Original Jupyternotebook: "OneDrive\文件\Jupyter Notebooks\class imbalance lab\" 
    DataRobot Jupyternotebook: "GitHub\examples-for-data-scientists\My class imbalance question.ipynb" 
    Rename : "GitHub\examples-for-data-scientists\Random TF 50-50.ipynb" 因為原來問題不是 imbalance 且已澄清。

In [6]:
%run ../forth.py

reDef unknown
reDef -->
p e f o r t h    v1.26
source code http://github.com/hcchengithub/peforth
Type 'peforth.ok()' to enter forth interpreter, 'exit' to come back.

In [1]:
import datarobot as dr 
import pandas as pd
import numpy as np
import math

In [31]:
feature_width = 2000
np.random.seed(0)  # 做實驗這個很重要！固定 dataset.
x = np.random.rand(300,feature_width)
data = pd.DataFrame(np.array(x))
data.head()

,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
0,0.548814,0.715189,0.602763,0.544883,0.423655,0.645894,0.437587,0.891773,0.963663,0.383442,...,0.173193,0.875200,0.027653,0.660339,0.414439,0.791282,0.721198,0.480108,0.643864,0.501773
1,0.811518,0.476084,0.523156,0.250521,0.605043,0.302905,0.577284,0.169678,0.159469,0.417030,...,0.385470,0.241751,0.187770,0.404680,0.119904,0.349639,0.434874,0.830003,0.932806,0.308338
2,0.292642,0.566518,0.137414,0.349712,0.053216,0.379068,0.114151,0.561813,0.641594,0.987092,...,0.058247,0.337073,0.690050,0.600069,0.433219,0.104233,0.139528,0.696523,0.483697,0.339551
3,0.374794,0.428686,0.683057,0.600948,0.070483,0.157478,0.070556,0.034590,0.776005,0.850959,...,0.550645,0.189118,0.693432,0.212707,0.689958,0.923183,0.941301,0.801828,0.539145,0.837219
4,0.457760,0.376918,0.702335,0.207324,0.074280,0.366027,0.340635,0.120524,0.854562,0.668148,...,0.694983,0.194607,0.114037,0.262116,0.735502,0.550447,0.397151,0.758430,0.023787,0.813575

# 大於小於 0.5 

不能更簡單了，純亂數 2000 features 其中一條以 0.5 為界，大於等於 0.5 者 target 為 True.

In [32]:
# 切一半，是否 >= 0.5 
for i in range(data.shape[0]):
    data.loc[i,0] = True if data.loc[i,1] >= 0.5 else False

data.head()

,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
0,True,0.715189,0.602763,0.544883,0.423655,0.645894,0.437587,0.891773,0.963663,0.383442,...,0.173193,0.875200,0.027653,0.660339,0.414439,0.791282,0.721198,0.480108,0.643864,0.501773
1,False,0.476084,0.523156,0.250521,0.605043,0.302905,0.577284,0.169678,0.159469,0.417030,...,0.385470,0.241751,0.187770,0.404680,0.119904,0.349639,0.434874,0.830003,0.932806,0.308338
2,True,0.566518,0.137414,0.349712,0.053216,0.379068,0.114151,0.561813,0.641594,0.987092,...,0.058247,0.337073,0.690050,0.600069,0.433219,0.104233,0.139528,0.696523,0.483697,0.339551
3,False,0.428686,0.683057,0.600948,0.070483,0.157478,0.070556,0.034590,0.776005,0.850959,...,0.550645,0.189118,0.693432,0.212707,0.689958,0.923183,0.941301,0.801828,0.539145,0.837219
4,False,0.376918,0.702335,0.207324,0.074280,0.366027,0.340635,0.120524,0.854562,0.668148,...,0.694983,0.194607,0.114037,0.262116,0.735502,0.550447,0.397151,0.758430,0.023787,0.813575

In [36]:
# 查看 the target feature
target_name = 0 # 試一下就知道，不是 '0' 而是 0 
data[0].head()

0     True
1    False
2     True
3    False
4    False
Name: 0, dtype: object

In [7]:
dr.Client(token=peforth.execute('api_token').pop(), endpoint=peforth.execute('endpoint').pop())

In [11]:
project_name = 'Random TF 50-50'

# 這一步過了好久，上網頁查看，發現 project 已經建立起來了，再過一會兒發現這裡也好了。
# 會重複 create 同名 project! 所以開既有的得用 dr.Project.get(project_id=project_id) 而非 create(), start() 之類
project = dr.Project.create(data, project_name = project_name)

到這裡資料已經餵進 DataRobot 了，後續用手動方式在網頁上操作。
- 發現沒有用的 features DR 很在行。所以這個問題答案就是進 model 前先處理過 features。
- [Start] 之後當然 Model > understand > feature impact, feature effect 很清楚知道哪些 feature 有關，那些無關。試試看 [Start] 之前可以做甚麼？ 答：光選好 target 就開始跑 EDA 了，有了 EDA 就有 feature importance 了。其他還能做甚麼？再探討。。。

In [12]:
project_id = dr.Project.list(search_params={'project_name':project_name})[0].id
project = dr.Project.get(project_id=project_id)
%f project_id -->
%f project -->

project_id --> 60d44cd52fe655eddea74226 (<class 'str'>)
project --> Project(Random TF 50-50) (<class 'datarobot.models.project.Project'>)

### click 過 pause button 它已經進入 pause 狀態
我之前從 UI 上 click 過 pause button 它已經進入 pause 狀態了。後來給三個 model 換選了 feature list 是真的已經都發動重跑了，但是 pause 狀態要 click 過才會鬆開。我沒看出來，所以用以下程式查看，一頓疑惑之後終於看出來了。

In [14]:
project.get_all_jobs() # 傳回 [ ] 空 list 表示 job queue 已經空了，但發動者很可能接著又發動新的 jobs。

[Job(model, status=queue), Job(model, status=queue), Job(model, status=queue)]

In [15]:
import time
while True:
    time.sleep(2); all_jobs_a = len(project.get_all_jobs())
    time.sleep(2); all_jobs_b = len(project.get_all_jobs())
    if all_jobs_a + all_jobs_b : 
        project.wait_for_autopilot() # 當前 modeling 總會全部結束，但發動者很可能接著又發動新的 jobs。。。
        continue
    break

In progress: 3, queued: 0 (waited: 0s)
In progress: 1, queued: 0 (waited: 0s)
In progress: 1, queued: 0 (waited: 0s)
In progress: 1, queued: 0 (waited: 0s)
In progress: 1, queued: 0 (waited: 0s)
In progress: 1, queued: 0 (waited: 0s)
In progress: 0, queued: 0 (waited: 0s)

### 比對結果

光看 `training_predictions.get_all_as_dataframe()` 的結果看不出來，與 data 比對方知對錯。
從 QT bug title parser 抄已經研究過成功的 snippets 過來跑。

In [49]:
# model_id 用手工上 UI 取得
model_id = '60d4938bad35826f3cc41cbe'
# model_id = '60d4939cdb70fba273c41bb5'
# model_id = '60d493a291bd4a2232c41d8e'
model = dr.Model.get(project=project.id,model_id=model_id)
model

Model('RandomForest Classifier (Gini)')

In [50]:
training_predictions_job = model.request_training_predictions(dr.enums.DATA_SUBSET.HOLDOUT)
training_predictions = training_predictions_job.get_result_when_complete()
training_predictions

In [51]:
# Fetch training predictions as data frame
df_predict_holdout = training_predictions.get_all_as_dataframe()
df_predict_holdout.head()

   row_id partition_id  prediction  class_1.0  class_0.0
0      11      Holdout         0.0        0.0        1.0
1      15      Holdout         1.0        1.0        0.0
2      16      Holdout         0.0        0.0        1.0
3      18      Holdout         0.0        0.0        1.0
4      26      Holdout         0.0        0.0        1.0

In [52]:
# 瞧一瞧所有的 prediction 結果。等下要拿來跟 dataset 比對。
%f df_predict_holdout :> ['prediction'] list --> cr
%f df_predict_holdout :> ['row_id'] list -->

df_predict_holdout :> ['prediction'] list --> [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0] (<class 'list'>)

df_predict_holdout :> ['row_id'] list --> [11, 15, 16, 18, 26, 40, 43, 45, 56, 63, 65, 67, 69, 70, 73, 84, 87, 95, 98, 99, 105, 106, 109, 115, 116, 120, 140, 143, 144, 153, 154, 160, 161, 177, 179, 192, 195, 196, 198, 199, 200, 201, 206, 207, 208, 224, 226, 227, 231, 232, 237, 248, 251, 259, 260, 269, 283, 287, 288, 289] (<class 'list'>)

In [53]:
# prediction 結果跟 dataset 比對。用 prediction 0 的 index 去算 dataset 的 sum 就是 FN
indexs = list(df_predict_holdout.query('prediction == 0.0')['row_id'])
%f indexs count nip -->
positives = [data[target_name].iloc[i] for i in indexs]    
%f # FN 越少越好
sum(positives)

indexs count nip --> 32 (<class 'int'>)
FN 越少越好

0

In [54]:
# prediction 結果跟 dataset 比對。用 prediction 1 的 index 去算 dataset 的 sum 就是 TP
indexs = list(df_predict_holdout.query('prediction == 1.0')['row_id'])
%f indexs count nip -->
positives = [data[target_name].iloc[i] for i in indexs]    
%f # TP 越接近越好
sum(positives)

indexs count nip --> 28 (<class 'int'>)
TP 越接近越好

28

# 取平方根 regression

In [55]:
# 取平方根
for i in range(data.shape[0]):
    data.loc[i,2] = math.sqrt(data.loc[i,3])

data.head()

,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
0,True,0.715189,0.738162,0.544883,0.423655,0.645894,0.437587,0.891773,0.963663,0.383442,...,0.173193,0.875200,0.027653,0.660339,0.414439,0.791282,0.721198,0.480108,0.643864,0.501773
1,False,0.476084,0.500520,0.250521,0.605043,0.302905,0.577284,0.169678,0.159469,0.417030,...,0.385470,0.241751,0.187770,0.404680,0.119904,0.349639,0.434874,0.830003,0.932806,0.308338
2,True,0.566518,0.591365,0.349712,0.053216,0.379068,0.114151,0.561813,0.641594,0.987092,...,0.058247,0.337073,0.690050,0.600069,0.433219,0.104233,0.139528,0.696523,0.483697,0.339551
3,False,0.428686,0.775208,0.600948,0.070483,0.157478,0.070556,0.034590,0.776005,0.850959,...,0.550645,0.189118,0.693432,0.212707,0.689958,0.923183,0.941301,0.801828,0.539145,0.837219
4,False,0.376918,0.455329,0.207324,0.074280,0.366027,0.340635,0.120524,0.854562,0.668148,...,0.694983,0.194607,0.114037,0.262116,0.735502,0.550447,0.397151,0.758430,0.023787,0.813575

In [58]:
# excel 檢驗確實 2*2 == 3 
data[[2,3]].head()

          2         3
0  0.738162  0.544883
1  0.500520  0.250521
2  0.591365  0.349712
3  0.775208  0.600948
4  0.455329  0.207324

In [60]:
project_name = 'Random sqrt regression'

# 執行一次就不用了，以免重複建立新 project 
project = dr.Project.create(data, project_name = project_name)

In [62]:
project_id = dr.Project.list(search_params={'project_name':project_name})[0].id
project = dr.Project.get(project_id=project_id)
%f project_id -->
%f project -->

project_id --> 60d56d83b569b0702663f86d (<class 'str'>)
project --> Project(Random sqrt regression) (<class 'datarobot.models.project.Project'>)

In [65]:
project.set_target(
    target = '2',
    worker_count = 10,
    mode = dr.AUTOPILOT_MODE.QUICK
)
project.wait_for_autopilot()

In progress: 9, queued: 0 (waited: 0s)
In progress: 9, queued: 0 (waited: 2s)
In progress: 9, queued: 0 (waited: 4s)
In progress: 9, queued: 0 (waited: 6s)
In progress: 9, queued: 0 (waited: 9s)
In progress: 9, queued: 0 (waited: 12s)
In progress: 9, queued: 0 (waited: 17s)
In progress: 9, queued: 0 (waited: 25s)
In progress: 8, queued: 0 (waited: 39s)
In progress: 5, queued: 0 (waited: 61s)
In progress: 4, queued: 0 (waited: 82s)
In progress: 2, queued: 0 (waited: 103s)
In progress: 2, queued: 0 (waited: 124s)
In progress: 2, queued: 0 (waited: 146s)
In progress: 10, queued: 6 (waited: 167s)
In progress: 10, queued: 6 (waited: 189s)
In progress: 0, queued: 0 (waited: 211s)

### 比對結果

光看 `training_predictions.get_all_as_dataframe()` 的結果看不出來，與 data 比對方知對錯。

In [66]:
# model_id 用手工上 UI 取得
model_id = '60d5730ea597d43c877de02a'
model = dr.Model.get(project=project.id,model_id=model_id)
model

Model('Light Gradient Boosting on ElasticNet Predictions ')

In [67]:
training_predictions_job = model.request_training_predictions(dr.enums.DATA_SUBSET.HOLDOUT)
training_predictions = training_predictions_job.get_result_when_complete()
training_predictions

In [68]:
# Fetch training predictions as data frame
df_predict_holdout = training_predictions.get_all_as_dataframe()
df_predict_holdout.head()

   row_id partition_id  prediction
0       6      Holdout    0.708644
1       7      Holdout    0.923270
2      22      Holdout    0.473917
3      24      Holdout    0.864413
4      29      Holdout    0.570743

In [83]:
# 照 holdout 的 index 到 data 裡去把標準答案 target 挑出來
indexs = list(df_predict_holdout['row_id'])
%f indexs count nip -->
targets = [data[2].iloc[i] for i in indexs]    
targets[:4]

indexs count nip --> 60 (<class 'int'>)

[0.7068776388172562,
 0.9240793991522077,
 0.4707804875496471,
 0.8642085498857117]

In [85]:
# 包裝成 DataFrame 
answers = pd.DataFrame(targets, index=indexs, columns=['target'])
answers.head()

      target
6   0.706878
7   0.924079
22  0.470780
24  0.864209
29  0.568861

In [90]:
# 並放目視比對
results = pd.merge(df_predict_holdout,answers, left_on='row_id', right_index=True)
results.head()

   row_id partition_id  prediction    target
0       6      Holdout    0.708644  0.706878
1       7      Holdout    0.923270  0.924079
2      22      Holdout    0.473917  0.470780
3      24      Holdout    0.864413  0.864209
4      29      Holdout    0.570743  0.568861

In [92]:
%f results :> ['prediction'][0] -->
%f results :> ['target'][0] -->

results :> ['prediction'][0] --> 0.7086444758897985 (<class 'numpy.float64'>)
results :> ['target'][0] --> 0.7068776388172562 (<class 'numpy.float64'>)

In [95]:
# 弄出新的 column 'is_bigger' 
# https://stackoverflow.com/questions/51499385/how-to-add-values-to-a-new-column-in-pandas-dataframe
results.at[0, 'is_bigger'] = True
# df.at[index, 'new_column'] = new_value

In [96]:
results.head()

   row_id partition_id  prediction    target is_bigger
0       6      Holdout    0.708644  0.706878      True
1       7      Holdout    0.923270  0.924079       NaN
2      22      Holdout    0.473917  0.470780       NaN
3      24      Holdout    0.864413  0.864209       NaN
4      29      Holdout    0.570743  0.568861       NaN

In [101]:
for i in range(results.shape[0]):
    results.loc[i,'is_bigger'] = results['prediction'][i] > results['target'][i]
    # data.loc[i,2] = math.sqrt(data.loc[i,3])

In [103]:
results

    row_id partition_id  prediction    target is_bigger
0        6      Holdout    0.708644  0.706878      True
1        7      Holdout    0.923270  0.924079     False
2       22      Holdout    0.473917  0.470780      True
3       24      Holdout    0.864413  0.864209      True
4       29      Holdout    0.570743  0.568861      True
5       31      Holdout    0.628410  0.628489     False
6       40      Holdout    0.565261  0.562815      True
7       59      Holdout    0.741739  0.743094     False
8       66      Holdout    0.990630  0.988012      True
9       67      Holdout    0.251626  0.251298      True
10      69      Holdout    0.636970  0.636930      True
11      73      Holdout    0.914518  0.914720     False
12      77      Holdout    0.709824  0.710035     False
13      80      Holdout    0.651599  0.651547      True
14      92      Holdout    0.473050  0.469630      True
15      93      Holdout    0.987575  0.986082      True
16      95      Holdout    0.648332  0.648411     False
17      97      Holdout    0.781337  0.779818      True
18     101      Holdout    0.902734  0.904547     False
19     102      Holdout    0.363833  0.376769     False
20     106      Holdout    0.331428  0.318615      True
21     108      Holdout    0.341939  0.338575      True
22     111      Holdout    0.830613  0.832943     False
23     112      Holdout    0.661066  0.660550      True
24     115      Holdout    0.966835  0.972869     False
25     125      Holdout    0.844583  0.845953     False
26     127      Holdout    0.470309  0.465973      True
27     129      Holdout    0.723799  0.723124      True
28     134      Holdout    0.875555  0.876788     False
29     146      Holdout    0.719855  0.719713      True
30     148      Holdout    0.860697  0.859774      True
31     155      Holdout    0.799263  0.800254     False
32     157      Holdout    0.869400  0.870225     False
33     160      Holdout    0.673362  0.672065      True
34     163      Holdout    0.418013  0.421101     False
35     164      Holdout    0.753011  0.752499      True
36     165      Holdout    0.793729  0.789671      True
37     167      Holdout    0.900733  0.898017      True
38     186      Holdout    0.395579  0.396886     False
39     187      Holdout    0.174401  0.213362     False
40     198      Holdout    0.543535  0.542972      True
41     200      Holdout    0.734284  0.736807     False
42     201      Holdout    0.516562  0.512912      True
43     214      Holdout    0.936802  0.933171      True
44     217      Holdout    0.659609  0.659173      True
45     219      Holdout    0.852505  0.851776      True
46     222      Holdout    0.968783  0.974118     False
47     224      Holdout    0.585943  0.584651      True
48     225      Holdout    0.478247  0.476485      True
49     229      Holdout    0.298243  0.313791     False
50     230      Holdout    0.588540  0.587416      True
51     234      Holdout    0.914319  0.914585     False
52     247      Holdout    0.679545  0.680294     False
53     252      Holdout    0.491873  0.494006     False
54     253      Holdout    0.442428  0.445741     False
55     262      Holdout    0.760204  0.758440      True
56     275      Holdout    0.296187  0.309677     False
57     276      Holdout    0.347525  0.348718     False
58     288      Holdout    0.626370  0.626460     False
59     297      Holdout    0.837422  0.838028     False